version: '3'

services: 
  postgresql:
    build: 
      dockerfile: ./postgresql.dockerfile
      context: .
    image: mateusjbarbosa/mass_schedule_postgresql
    container_name: mass_schedule_postgresql
    restart: always
    networks: 
      - network
    ports: 
      - "5432:5432"
    volumes: 
      - data:/data

  api:
    build: 
      dockerfile: ./node.dockerfile
      context: .
    image: mateusjbarbosa/mass_schedule_api
    container_name: mass_schedule_api
    environment:
      WAIT_HOSTS: postgresql:5432
      WAIT_SLEEP_INTERVAL: 10
      WAIT_HOSTS_TIMEOUT: 120
    networks: 
      - network
    ports: 
      - "3000:3000"
    depends_on: 
      - postgresql
    
volumes: 
  data:

networks: 
  network:
    driver: bridge