version: '3'

services: 
  postgresql:
    build: 
      dockerfile: ./dockerfiles/postgresql.dockerfile
      context: .
    image: mateusjbarbosa/mass_schedule_postgresql
    container_name: mass_schedule_postgresql
    networks: 
      - network
    ports: 
      - "5432:5432"
    volumes: 
      - data:/data

  pgadmin:
    build: 
      dockerfile: ./dockerfiles/pgadmin.dockerfile
      context: .
    image: mateusjbarbosa/mass_schedule_pgadmin
    container_name: mass_schedule_pgadmin
    networks: 
      - network
    ports: 
      - "3001:3001"
    depends_on: 
      - postgresql

  api:
    build: 
      dockerfile: ./dockerfiles/node.dockerfile
      context: .
    image: mateusjbarbosa/mass_schedule_api
    container_name: mass_schedule_api
    networks: 
      - network
    ports: 
      - "3000:3000"
    depends_on: 
      - postgresql
    
volumes: 
  data:

networks: 
  network:
    driver: bridge